project:
  type: website
  output-dir: docs
  
website:
  title: "Meu Mundo:: Olá Mundo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/davibps/meu_site
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Daví Barbosa Pereira de Sousa"

format:
  html:
    theme: cerulean
    toc: true

editor: source

